version: '3'
services:
  mysql:
    image: mysql:5.7.21
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_seek_job_test
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root

  microservice:
    environment:
      DATABASE_PORT: 3306
    ports:
      - "9000:9000"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/app
      - /var/app/node_modules
      - /var/app/coverage
      - /var/app/logs
    links:
      - "mysql:mysql-docker"